version: "3"
services:
  app:
    image: "ghcr.io/luketainton/docker-radius:latest"
    restart: "unless-stopped"
    volumes:
      - "./clients.conf:/etc/raddb/clients.conf"
      - "./users:/etc/raddb/users"
      - "./radiusd.conf:/etc/raddb/radiusd.conf"
    ports:
      - "1812:1812/udp"
      - "18080:8080/tcp"
